### ISSUE TITLE
Does not play ball with the link field plugin

### ISSUE THREAD

**Issue by bleepsandblops** [markhuot/craft-pest#82] opened 2023-01-18 14:49 UTC
With Pest activated, when creating a [new link field](https://github.com/sebastian-lenz/craft-linkfield), I get:
`Calling unknown method: lenz\linkfield\fields\LinkField::factoryTypeHint() in "__string_template__2feea56560234f273691feaa93ef7d61" at line 7`

**Comment by markhuot** [comment] 2023-01-20 22:48
Is the `craft-pest` plugin installed in the Craft UI? There’s a behavior that provides that method in the plugin `init` and the only reason I can think it would go missing would be if the plugin is not enabled.

Related: I’m looking at having everything run without needing to install the plugin. But that’s still a PR away and not in a release yet.

**Comment by JodebaDigitalPulse** [comment] 2023-01-30 08:29
I have the same issue, the two plugins are enabled. [The registration of the behaviour](https://github.com/markhuot/craft-pest/blob/acfa055a8b31bb96b9bda55a65e85f8e41303ac7/src/Pest.php#L65) is executed (I can dump something there before errors are thrown).

Full output:
./vendor/bin/pest --verbose

   FAIL  Tests\ExampleTest
  ⨯ it Loads the homepage

  ---

  • Tests\ExampleTest > it Loads the homepage
   PHPUnit\Framework\ExceptionWrapper 

  Calling unknown method: lenz\linkfield\fields\LinkField::factoryTypeHint() in "__string_template__2feea56560234f273691feaa93ef7d61" at line 7

  at vendor/craftcms/cms/src/helpers/Template.php:116
    112▕             // Copy twig_get_attribute()'s BadMethodCallException handling
    113▕             if ($ignoreStrictCheck || !$env->isStrictVariables()) {
    114▕                 return null;
    115▕             }
  ➜ 116▕             throw new RuntimeError($e->getMessage(), -1, $source);
    117▕         }
    118▕     }
    119▕
    120▕     /**

  1   vendor/phpunit/phpunit/src/Framework/TestCase.php:904
      PHPUnit\Framework\TestResult::run()

  2   vendor/phpunit/phpunit/src/Framework/TestSuite.php:675
      PHPUnit\Framework\TestCase::run()

  3   vendor/phpunit/phpunit/src/Framework/TestSuite.php:675
      PHPUnit\Framework\TestSuite::run()

  4   vendor/phpunit/phpunit/src/TextUI/TestRunner.php:653
      PHPUnit\Framework\TestSuite::run()

  5   vendor/phpunit/phpunit/src/TextUI/Command.php:144
      PHPUnit\TextUI\TestRunner::run()

  6   vendor/pestphp/pest/src/Console/Command.php:119
      PHPUnit\TextUI\Command::run()

  7   vendor/pestphp/pest/bin/pest:62
      Pest\Console\Command::run()

  8   vendor/pestphp/pest/bin/pest:63
      {closure}()

  9   vendor/bin/pest:120
      include("*******/vendor/pestphp/pest/bin/pest")

**Comment by markhuot** [comment] 2023-01-30 19:07
Ah, this is because the field doesn't call `parent::behaviors()` so the `EVENT_DEFINE_BEHAVIORS` is never run.

Link field inherits from `ForeignField` which defines it's `behaviors()` as,

https://github.com/sebastian-lenz/craft-utils/blob/86403435fdfcab499edd1b363bafc46cf4c1fb4d/src/foreignField/ForeignField.php#L55-L61

Which overrides the default functionality of,

https://github.com/craftcms/cms/blob/ea55235e5a9677aa577f3a701dd4eaa04c2010b7/src/base/Model.php#L96-L107

This fix will be that `ForeignField` needs to call the `parent` in order to retain this behavior. I've opened a PR with a potential fix, https://github.com/sebastian-lenz/craft-utils/pull/4.

**Comment by JodebaDigitalPulse** [comment] 2023-01-31 07:40
thx! 🙌

**Comment by markhuot** [comment] 2023-02-04 11:39
I'm going to close this issue since the root cause is not in `craft-pest`. Hopefully https://github.com/sebastian-lenz/craft-utils/pull/4 merges soon and resolves this! Feel free to jump over to that PR and submit bump the thread if you have more questions.

**Closed by markhuot** 2023-02-04 11:39 UTC
