### ISSUE TITLE
Craft Commerce: 404 on form request without action

### ISSUE THREAD

**Issue by ostark** [markhuot/craft-pest#31] opened 2022-10-12 14:15 UTC
This test does not pass

```php
<?php

test('checkout as a guest', function() {

    $this->get('/product/san-quentin-24')
        ->assertOk()
        ->form('#buy form')
        ->submit()
        ->assertOk();

});
```

Since there is no action attribute on the form element, I tried to tweak it the submit() method 

```
        $uri = $this->form->getUri();

        if ("" == $this->form->getFormNode()->getAttribute('action')) {
              // use previous uri  
              $uri = \Craft::$app->getRequest()->getUrl();
        }

        $request = new RequestBuilder(
            $this->form->getMethod(),
            $uri
        );
```
... but without success.

the `->getFields()` output looks okay

```
 Array &0 (
      'CRAFT_CSRF_TOKEN' => 'G6qIJCT8krJi_fc...='
      'action' => 'commerce/cart/update-cart'
      'successMessage' => 'ffe3ef7acc2f7371...4eb8e23c0df3Added San Quentin 24 to the cart.'
      'purchasableId' => '325'
  )
```
Any idea?

**Comment by markhuot** [comment] 2022-10-12 20:36
I'll clone it down and have a look. I have a `// @todo` to better handle URL/URI parsing in the request builder so I think I know where Yii is getting tripped up.

**Comment by ostark** [comment] 2022-10-13 11:44
So far `submit()` creates a new POST request, follows a redirect, and returns a 200 OK, which is a bit unexpected to me.

I'd prefer something like this

```php
# no redirect, but assertions allowed
->submit()
->assertRedirectTo('/checkout/next-step')
```

```php
# to support further chaining
->submit()
->assertRedirectTo('/checkout/next-step')
->follow()
```

**Comment by markhuot** [comment] 2022-10-13 13:18
Well that is _surprising_. I'm not sure why it's following that redirect. I'll take a look. Agreed that being explicit about following redirects is the right choice.

**Comment by markhuot** [comment] 2022-10-13 14:07
Yuck, I believe the issue is that Craft's `{% redirect %}` tag (and other redirect methods) throw a `->end()` in there which is short circuiting the `RequestHandler`'s logic. Will look for an override.

![image](https://user-images.githubusercontent.com/48975/195619336-c48960d3-5f6b-4f53-8b62-360932a533af.png)

It's that `->end()` on line 39 of this compiled Twig template that causes issues.

**Comment by ostark** [comment] 2022-10-13 15:02
OverwriteEverything ™

**Comment by markhuot** [comment] 2022-10-13 15:31
Should be fixed with https://github.com/markhuot/craft-pest/pull/33. Waiting on the test suite to run.

**Comment by markhuot** [comment] 2022-10-13 17:41
This is merged. I'm going to close this issue. Feel free to reopen if you're still having problems.

**Closed** 2022-10-13 17:42 UTC
